version: '3.4'

services:
#Micro services
  paymentapi:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment/PaymentApi/Dockerfile
    depends_on: 
      - messagebroker
      - db-mssql
    networks:
      - application_network

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/OrderApi/Dockerfile
    depends_on: 
      - messagebroker
      - db-mssql
    networks:
      - application_network

#Message broker
  messagebroker:
    image: rabbitmq:3-management-alpine
    container_name: 'messagebroker-rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - application_network

#Databases
  db-mssql:
    container_name: orderdb-mssql
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - 1433:1433
    volumes:
      - .\apps\mssql\data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    networks:
      - application_network

networks:
    application_network:
        driver: bridge
