// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentApi.Context;

#nullable disable

namespace PaymentApi.Migrations
{
    [DbContext(typeof(PaymentContext))]
    partial class PaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentDomain.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PaymentDomain.Models.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = "_d460d59f-2318-4639-96b7-864565622235-C796709D1E724868BABC48CB5E8060FA",
                            Amount = 0m,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 45, 11, 343, DateTimeKind.Utc).AddTicks(6970),
                            OrderId = "_d460d59f-2318-4639-96b7-864565622235-FDBA032C106412A2489424CD9884837F"
                        },
                        new
                        {
                            Id = "_d460d59f-2318-4639-96b7-864565622235-F0A8239D5611FE5236BB7DAE770FCC80",
                            Amount = 0m,
                            CreatedAt = new DateTime(2023, 4, 28, 19, 45, 11, 343, DateTimeKind.Utc).AddTicks(7041),
                            OrderId = "_d460d59f-2318-4639-96b7-864565622235-7D4967760580FE648A2BFCF8B6358FAA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
