name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the order api Docker image
      run: docker build . --file ./Cinepolis/Services/Order/Dockerfile --tag orderapi:$(date +%s)
